# Generated by Django 2.2.3 on 2020-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(choices=[('STU', 'Student'), ('PRO', 'Professional'), ('HOB', 'Hobbyist')], default='STU', max_length=3),
        ),
    ]
